
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 29 00:31:55 CST 2015
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVDER = 6;
  public static final int MENOS = 8;
  public static final int CADENA = 16;
  public static final int IGUAL = 23;
  public static final int DECIMAL = 15;
  public static final int DIVIDIDO = 10;
  public static final int RIMPRIMIR = 18;
  public static final int PARIZQ = 3;
  public static final int CONCAT = 11;
  public static final int PARDER = 4;
  public static final int UMENOS = 17;
  public static final int POR = 9;
  public static final int EOF = 0;
  public static final int RELSE = 22;
  public static final int RIF = 21;
  public static final int error = 1;
  public static final int MENQUE = 12;
  public static final int IDENTIFICADOR = 24;
  public static final int RMIENTRAS = 19;
  public static final int ENTERO = 14;
  public static final int MAYQUE = 13;
  public static final int MAS = 7;
  public static final int RNUMERO = 20;
  public static final int LLAVIZQ = 5;
  public static final int PTCOMA = 2;
}

